import fs from "node:fs";

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
const JPEG_SOI = Buffer.from([0xff, 0xd8]);
const C2PA_MANIFEST_STORE_UUID = Buffer.from("6332706100110010800000aa00389b71", "hex");

export interface C2paStripResult {
  bytes: Buffer;
  format: "PNG" | "JPEG" | "WebP";
  removedItems: number;
  removedBytes: number;
}

interface JpegSegment {
  marker: number;
  start: number;
  end: number;
  payload: Buffer;
}

/**
 * Removes C2PA/JUMBF metadata without decoding or re-encoding image pixels.
 * Supported containers match the formats accepted and generated by Marketing Hub.
 */
export function stripC2pa(input: Uint8Array, options: { stripAllJpegJumbf?: boolean } = {}): C2paStripResult {
  const bytes = Buffer.from(input);
  if (bytes.subarray(0, PNG_SIGNATURE.length).equals(PNG_SIGNATURE)) return stripPng(bytes);
  if (bytes.subarray(0, JPEG_SOI.length).equals(JPEG_SOI)) return stripJpeg(bytes, Boolean(options.stripAllJpegJumbf));
  if (bytes.subarray(0, 4).toString("ascii") === "RIFF" && bytes.subarray(8, 12).toString("ascii") === "WEBP") return stripWebp(bytes);
  throw new Error("Unsupported image format; C2PA stripping supports PNG, JPEG, and WebP.");
}

export function writeC2paStrippedImage(filePath: string, bytes: Uint8Array) {
  const result = stripC2pa(bytes);
  fs.writeFileSync(filePath, result.bytes);
  return result;
}

export function stripC2paFromFile(filePath: string) {
  return writeC2paStrippedImage(filePath, fs.readFileSync(filePath));
}

function stripPng(bytes: Buffer): C2paStripResult {
  const kept: Buffer[] = [bytes.subarray(0, PNG_SIGNATURE.length)];
  let offset = PNG_SIGNATURE.length;
  let removedItems = 0;
  let removedBytes = 0;

  while (offset < bytes.length) {
    if (offset + 12 > bytes.length) throw new Error("Truncated PNG chunk.");
    const chunkLength = bytes.readUInt32BE(offset);
    const chunkType = bytes.subarray(offset + 4, offset + 8).toString("ascii");
    const chunkEnd = offset + 12 + chunkLength;
    if (chunkEnd > bytes.length) throw new Error("Invalid PNG chunk length.");
    if (chunkType === "caBX") {
      removedItems += 1;
      removedBytes += chunkEnd - offset;
    } else {
      kept.push(bytes.subarray(offset, chunkEnd));
    }
    offset = chunkEnd;
  }

  return { bytes: Buffer.concat(kept), format: "PNG", removedItems, removedBytes };
}

function stripJpeg(bytes: Buffer, stripAllJpegJumbf: boolean): C2paStripResult {
  const { segments, scanPayloadStart } = parseJpegSegmentsUntilScan(bytes);
  const remove = new Set<number>();
  let index = 0;

  while (index < segments.length) {
    if (!isJumbfApp11(segments[index])) {
      index += 1;
      continue;
    }
    const runStart = index;
    let runEnd = index + 1;
    while (runEnd < segments.length && isJumbfApp11(segments[runEnd])) runEnd += 1;
    const runPayload = Buffer.concat(segments.slice(runStart, runEnd).map((segment) => segment.payload));
    const looksLikeC2pa = runPayload.toString("latin1").toLowerCase().includes("c2pa") || runPayload.indexOf(C2PA_MANIFEST_STORE_UUID) !== -1;
    if (stripAllJpegJumbf || looksLikeC2pa) for (let runIndex = runStart; runIndex < runEnd; runIndex += 1) remove.add(runIndex);
    index = runEnd;
  }

  const kept: Buffer[] = [JPEG_SOI];
  let removedBytes = 0;
  segments.forEach((segment, segmentIndex) => {
    const raw = bytes.subarray(segment.start, segment.end);
    if (remove.has(segmentIndex)) removedBytes += raw.length;
    else kept.push(raw);
  });
  kept.push(bytes.subarray(scanPayloadStart));
  return { bytes: Buffer.concat(kept), format: "JPEG", removedItems: remove.size, removedBytes };
}

function parseJpegSegmentsUntilScan(bytes: Buffer) {
  if (!bytes.subarray(0, 2).equals(JPEG_SOI)) throw new Error("Not a JPEG image.");
  const segments: JpegSegment[] = [];
  let offset = 2;

  while (offset < bytes.length) {
    const markerStart = offset;
    if (bytes[offset] !== 0xff) throw new Error("Unexpected JPEG data before Start Of Scan.");
    while (offset < bytes.length && bytes[offset] === 0xff) offset += 1;
    if (offset >= bytes.length) throw new Error("Truncated JPEG marker.");
    const marker = bytes[offset];
    offset += 1;
    if (marker === 0x00) throw new Error("Unexpected stuffed JPEG byte before Start Of Scan.");

    const hasNoLength = marker === 0x01 || marker === 0xd8 || marker === 0xd9 || (marker >= 0xd0 && marker <= 0xd7);
    if (hasNoLength) {
      segments.push({ marker, start: markerStart, end: offset, payload: Buffer.alloc(0) });
      continue;
    }
    if (offset + 2 > bytes.length) throw new Error("Truncated JPEG segment length.");
    const segmentLength = bytes.readUInt16BE(offset);
    const segmentEnd = offset + segmentLength;
    if (segmentLength < 2 || segmentEnd > bytes.length) throw new Error("Invalid JPEG segment length.");
    segments.push({ marker, start: markerStart, end: segmentEnd, payload: bytes.subarray(offset + 2, segmentEnd) });
    offset = segmentEnd;
    if (marker === 0xda) return { segments, scanPayloadStart: offset };
  }
  throw new Error("JPEG image has no Start Of Scan.");
}

function isJumbfApp11(segment: JpegSegment) {
  return segment.marker === 0xeb && segment.payload.subarray(0, 2).toString("ascii") === "JP";
}

function stripWebp(bytes: Buffer): C2paStripResult {
  const kept: Buffer[] = [bytes.subarray(0, 12)];
  let offset = 12;
  let removedItems = 0;
  let removedBytes = 0;

  while (offset < bytes.length) {
    if (offset + 8 > bytes.length) throw new Error("Truncated WebP chunk.");
    const chunkType = bytes.subarray(offset, offset + 4).toString("ascii");
    const chunkLength = bytes.readUInt32LE(offset + 4);
    const chunkEnd = offset + 8 + chunkLength + (chunkLength % 2);
    if (chunkEnd > bytes.length) throw new Error("Invalid WebP chunk length.");
    if (chunkType === "C2PA") {
      removedItems += 1;
      removedBytes += chunkEnd - offset;
    } else {
      kept.push(bytes.subarray(offset, chunkEnd));
    }
    offset = chunkEnd;
  }

  const output = Buffer.concat(kept);
  output.writeUInt32LE(output.length - 8, 4);
  return { bytes: output, format: "WebP", removedItems, removedBytes };
}
