"use client";

import Link from "next/link";
import { FileClock, FlaskConical, MicVocal, PenLine, Trash2, TriangleAlert } from "lucide-react";
import { apiRequest, ConnectionBadge, PageState, formatDate, useWorkspace } from "./workspace";
import { InlineOperation, useOperations } from "./operations";

export function RunsClient() {
  const workspace = useWorkspace();
  const operations = useOperations();
  if (!workspace.state) return <PageState loading={workspace.loading} error={workspace.error} retry={workspace.refresh}/>;
  const state = workspace.state;
  const items = [
    ...state.researchRuns.map((run) => ({ id: run.id, kind: "research" as const, name: run.name, status: run.status, startedAt: run.startedAt, completedAt: run.completedAt, contextIds: run.contextDocumentIds, count: run.resultCount, requestedCount: run.requestedCount, model: run.model, promptVersion: run.promptVersion, usage: run.usage, warnings: run.warnings, error: run.error })),
    ...state.outreachCampaigns.map((campaign) => ({ id: campaign.id, kind: "outreach" as const, name: campaign.name, status: campaign.status, startedAt: campaign.createdAt, completedAt: campaign.updatedAt, contextIds: campaign.contextDocumentIds, count: campaign.recipients.length, requestedCount: null, model: campaign.model, promptVersion: campaign.promptVersion, usage: campaign.usage, warnings: campaign.warnings, error: null })),
    ...state.contentCampaigns.map((campaign) => ({ id: campaign.id, kind: "content" as const, name: campaign.name, status: campaign.status, startedAt: campaign.createdAt, completedAt: campaign.updatedAt, contextIds: campaign.contextDocumentIds, count: campaign.posts.length, requestedCount: null, model: campaign.model, promptVersion: campaign.promptVersion, usage: campaign.usage, warnings: campaign.warnings, error: campaign.error })),
    ...state.speakerSpotlightBatches.map((batch) => ({ id: batch.id, kind: "spotlight" as const, name: `Speaker Spotlight · ${batch.speakerNames.join(", ")}`, status: batch.status, startedAt: batch.createdAt, completedAt: batch.completedAt, contextIds: [], count: batch.results.filter((result) => result.status === "completed").length, requestedCount: batch.results.length, model: batch.model, promptVersion: batch.promptVersion, usage: null, warnings: batch.warnings, error: batch.error }))
  ].sort((a, b) => b.startedAt.localeCompare(a.startedAt));

  async function remove(kind: "research" | "outreach" | "content" | "spotlight", id: string, name: string) {
    if (!confirm(`Delete “${name}” and its locally saved ${kind === "research" ? "leads and sources" : kind === "outreach" ? "recipient drafts" : kind === "spotlight" ? "speaker packages" : "posts and generated assets"}?`)) return;
    const route = kind === "research" ? "/api/research" : kind === "outreach" ? "/api/outreach" : kind === "spotlight" ? "/api/speaker-spotlights" : "/api/content";
    await apiRequest(`${route}?id=${id}`, { method: "DELETE" }); await workspace.refresh();
  }

  const visibleOperations = operations.operations.filter((operation) => operation.status !== "completed");
  return <div className="page runs-page"><header className="page-header split"><div><h1>Runs</h1><p className="lede">Reopen completed work, inspect failed runs, and keep provider and prompt metadata with every saved run.</p></div><ConnectionBadge state={state}/></header>
    {visibleOperations.length > 0 && <section className="section-block activity-section"><div className="section-heading"><div><h2>Recent activity</h2><p className="muted">Work that needs attention or can be resumed.</p></div></div><div className="operations-run-list">{visibleOperations.map((operation) => <InlineOperation key={operation.id} operation={operation}/>)}</div></section>}
    {items.length ? <section className="section-block saved-runs-section"><div className="section-heading"><div><h2>Saved runs</h2><p className="muted">{items.length} run{items.length === 1 ? "" : "s"} ready to reopen or inspect.</p></div></div><div className="run-list">{items.map((item) => <article className="run-card" key={`${item.kind}-${item.id}`}><span className={`run-kind ${item.kind}`}>{item.kind === "research" ? <FlaskConical/> : item.kind === "spotlight" ? <MicVocal/> : <PenLine/>}</span><div className="run-content"><div className="run-card-title"><div><span className="type-label">{item.kind}</span><h2>{item.name}</h2></div><span className={`badge ${item.status === "completed" || item.status === "reviewed" ? "success" : item.status === "failed" ? "danger" : "warning"}`}>{item.status.replaceAll("_", " ")}</span></div><div className="run-metadata"><span><strong>{item.count}{item.requestedCount ? ` / ${item.requestedCount}` : ""}</strong>{item.kind === "research" ? "results / requested" : item.kind === "outreach" ? "recipient drafts" : item.kind === "spotlight" ? "packages / requested" : "platform posts"}</span>{item.kind !== "spotlight" && <span><strong>{item.contextIds.length}</strong>context docs</span>}<span><strong>{item.model}</strong>model</span><span><strong>{item.promptVersion}</strong>prompt</span></div>{item.kind !== "spotlight" && <details><summary>Selected context</summary><ul>{item.contextIds.map((id) => <li key={id}>{state.contextDocuments.find((document) => document.id === id)?.title || `Deleted context (${id.slice(0, 8)})`}</li>)}</ul></details>}{item.usage && <details><summary>Usage metadata</summary><pre className="metadata-json">{JSON.stringify(item.usage, null, 2)}</pre></details>}{item.error && <div className="warnings"><TriangleAlert/><span>{item.error}</span></div>}{item.warnings.length > 0 && <details><summary>{item.warnings.length} warning{item.warnings.length === 1 ? "" : "s"}</summary><ul>{item.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></details>}<small>Started {formatDate(item.startedAt)} · {item.completedAt ? `Completed ${formatDate(item.completedAt)}` : "Not completed"}</small></div><div className="run-actions"><Link href={item.kind === "content" ? `/content?campaign=${item.id}` : item.kind === "outreach" ? `/leads?outreach=${item.id}` : item.kind === "spotlight" ? "/speaker-spotlight" : `/leads?run=${item.id}`} className="button secondary small">Reopen</Link><button className="icon-button danger-text" onClick={() => void remove(item.kind, item.id, item.name)} aria-label={`Delete ${item.name}`}><Trash2 size={16}/></button></div></article>)}</div></section> : <div className="empty-state"><FileClock/><h3>No saved runs</h3><p>Completed and failed research or content work will remain inspectable here.</p><div className="row-actions"><Link href="/leads" className="button">Find opportunities</Link><Link href="/content" className="button secondary">Create content</Link></div></div>}
  </div>;
}
